-- MySQL Script generated by MySQL Workbench
-- Tue Oct 24 22:58:52 2017
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='TRADITIONAL,ALLOW_INVALID_DATES';

-- -----------------------------------------------------
-- Schema Attendance
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema Attendance
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `Attendance` DEFAULT CHARACTER SET utf8 ;
USE `Attendance` ;

-- -----------------------------------------------------
-- Table `Attendance`.`Classroom`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `Attendance`.`Classroom` (
  `Semester` TINYINT NOT NULL,
  `Section_elective` CHAR(4) NOT NULL,
  PRIMARY KEY (`Semester`, `Section_elective`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `Attendance`.`Teacher`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `Attendance`.`Teacher` (
  `Teacher_id` CHAR(10) NOT NULL,
  `First_name` VARCHAR(100) NOT NULL,
  `Middle_name` VARCHAR(100) NULL,
  `Last_name` VARCHAR(100) NOT NULL,
  `Password` CHAR(77) NOT NULL,
  PRIMARY KEY (`Teacher_id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `Attendance`.`Student`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `Attendance`.`Student` (
  `USN` CHAR(10) NOT NULL,
  `First_name` VARCHAR(100) NOT NULL,
  `Middle_name` VARCHAR(100) NULL,
  `Last_name` VARCHAR(100) NOT NULL,
  `Password` CHAR(77) NOT NULL,
  `Semester` TINYINT NOT NULL,
  `Section` CHAR(1) NOT NULL,
  `Counselor` CHAR(10) NOT NULL,
  PRIMARY KEY (`USN`),
  CONSTRAINT `fk_Student_Classroom`
    FOREIGN KEY (`Semester` , `Section`)
    REFERENCES `Attendance`.`Classroom` (`Semester` , `Section_elective`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Student_Teacher1`
    FOREIGN KEY (`Counselor`)
    REFERENCES `Attendance`.`Teacher` (`Teacher_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;

CREATE INDEX `fk_Student_Classroom_idx` ON `Attendance`.`Student` (`Semester` ASC, `Section` ASC);

CREATE INDEX `fk_Student_Teacher1_idx` ON `Attendance`.`Student` (`Counselor` ASC);


-- -----------------------------------------------------
-- Table `Attendance`.`Subject`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `Attendance`.`Subject` (
  `Subject_code` CHAR(10) NOT NULL,
  `Subject_Name` VARCHAR(100) NOT NULL,
  `LB_AS` TINYINT NOT NULL,
  `Is_elective` TINYINT NOT NULL,
  `Semester` CHAR(2) NOT NULL,
  PRIMARY KEY (`Subject_code`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `Attendance`.`Completed_classes`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `Attendance`.`Completed_classes` (
  `Teacher_id` CHAR(10) NOT NULL,
  `Date_time` DATETIME NOT NULL,
  `Semester` TINYINT NOT NULL,
  `Section_elective` CHAR(4) NOT NULL,
  `Subject_Subject_code` CHAR(10) NOT NULL,
  PRIMARY KEY (`Teacher_id`, `Date_time`),
  CONSTRAINT `fk_table1_Teacher1`
    FOREIGN KEY (`Teacher_id`)
    REFERENCES `Attendance`.`Teacher` (`Teacher_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_table1_Classroom1`
    FOREIGN KEY (`Semester` , `Section_elective`)
    REFERENCES `Attendance`.`Classroom` (`Semester` , `Section_elective`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_table1_Subject1`
    FOREIGN KEY (`Subject_Subject_code`)
    REFERENCES `Attendance`.`Subject` (`Subject_code`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;

CREATE INDEX `fk_table1_Classroom1_idx` ON `Attendance`.`Completed_classes` (`Semester` ASC, `Section_elective` ASC);

CREATE INDEX `fk_table1_Subject1_idx` ON `Attendance`.`Completed_classes` (`Subject_Subject_code` ASC);


-- -----------------------------------------------------
-- Table `Attendance`.`Attendance`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `Attendance`.`Attendance` (
  `USN` CHAR(10) NOT NULL,
  `Teacher_id` CHAR(10) NOT NULL,
  `Date_time` DATETIME NOT NULL,
  PRIMARY KEY (`USN`, `Teacher_id`, `Date_time`),
  CONSTRAINT `fk_Attendance_Student1`
    FOREIGN KEY (`USN`)
    REFERENCES `Attendance`.`Student` (`USN`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Attendance_Completed_classes1`
    FOREIGN KEY (`Teacher_id` , `Date_time`)
    REFERENCES `Attendance`.`Completed_classes` (`Teacher_id` , `Date_time`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;

CREATE INDEX `fk_Attendance_Completed_classes1_idx` ON `Attendance`.`Attendance` (`Teacher_id` ASC, `Date_time` ASC);


-- -----------------------------------------------------
-- Table `Attendance`.`Schedule`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `Attendance`.`Schedule` (
  `Classroom_Semester` TINYINT NOT NULL,
  `Classroom_Section_elective` CHAR(4) NOT NULL,
  `Date_time` DATETIME NOT NULL,
  `Subject_Subject_code` CHAR(10) NULL,
  `Teacher_Teacher_id` CHAR(10) NULL,
  PRIMARY KEY (`Classroom_Semester`, `Classroom_Section_elective`, `Date_time`),
  CONSTRAINT `fk_Schedule_Classroom1`
    FOREIGN KEY (`Classroom_Semester` , `Classroom_Section_elective`)
    REFERENCES `Attendance`.`Classroom` (`Semester` , `Section_elective`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Schedule_Subject1`
    FOREIGN KEY (`Subject_Subject_code`)
    REFERENCES `Attendance`.`Subject` (`Subject_code`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Schedule_Teacher1`
    FOREIGN KEY (`Teacher_Teacher_id`)
    REFERENCES `Attendance`.`Teacher` (`Teacher_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;

CREATE INDEX `fk_Schedule_Subject1_idx` ON `Attendance`.`Schedule` (`Subject_Subject_code` ASC);

CREATE INDEX `fk_Schedule_Teacher1_idx` ON `Attendance`.`Schedule` (`Teacher_Teacher_id` ASC);


-- -----------------------------------------------------
-- Table `Attendance`.`Admin`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `Attendance`.`Admin` (
  `idAdmin` VARCHAR(50) NOT NULL,
  `Password` CHAR(77) NOT NULL,
  PRIMARY KEY (`idAdmin`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `Attendance`.`Marks`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `Attendance`.`Marks` (
  `Student_USN` CHAR(10) NOT NULL,
  `Subject_Subject_code` CHAR(10) NOT NULL,
  `Test1` TINYINT NULL,
  `Test2` TINYINT NULL,
  `Test3` TINYINT NULL,
  `AS_SS` TINYINT NULL,
  `Internal_Lab` TINYINT NULL,
  PRIMARY KEY (`Student_USN`, `Subject_Subject_code`),
  CONSTRAINT `fk_Marks_Student1`
    FOREIGN KEY (`Student_USN`)
    REFERENCES `Attendance`.`Student` (`USN`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Marks_Subject1`
    FOREIGN KEY (`Subject_Subject_code`)
    REFERENCES `Attendance`.`Subject` (`Subject_code`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;

CREATE INDEX `fk_Marks_Subject1_idx` ON `Attendance`.`Marks` (`Subject_Subject_code` ASC);


-- -----------------------------------------------------
-- Table `Attendance`.`Elective`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `Attendance`.`Elective` (
  `Student_USN` CHAR(10) NOT NULL,
  `Subject_Subject_code` CHAR(10) NOT NULL,
  `Classroom_Semester` TINYINT NOT NULL,
  `Classroom_Section_elective` CHAR(4) NOT NULL,
  PRIMARY KEY (`Student_USN`, `Subject_Subject_code`, `Classroom_Semester`, `Classroom_Section_elective`),
  CONSTRAINT `fk_Elective_Student1`
    FOREIGN KEY (`Student_USN`)
    REFERENCES `Attendance`.`Student` (`USN`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Elective_Subject1`
    FOREIGN KEY (`Subject_Subject_code`)
    REFERENCES `Attendance`.`Subject` (`Subject_code`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Elective_Classroom1`
    FOREIGN KEY (`Classroom_Semester` , `Classroom_Section_elective`)
    REFERENCES `Attendance`.`Classroom` (`Semester` , `Section_elective`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;

CREATE INDEX `fk_Elective_Subject1_idx` ON `Attendance`.`Elective` (`Subject_Subject_code` ASC);

CREATE INDEX `fk_Elective_Classroom1_idx` ON `Attendance`.`Elective` (`Classroom_Semester` ASC, `Classroom_Section_elective` ASC);


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
